### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by riponbanik** [Netflix/SimianArmy#155] opened 2014-12-17 20:02 UTC
Build error in windows -

:test
2014-12-17 21:57:03.329 - ERROR AbstractJanitor - [AbstractJanitor.java:298] Failed to clean up the resource 11.
java.lang.RuntimeException: Magic number of id.
        at com.netflix.simianarmy.janitor.TestAbstractJanitor.cleanup(TestAbstractJanitor.java:81)
        at com.netflix.simianarmy.janitor.AbstractJanitor.cleanupResources(AbstractJanitor.java:293)
        at com.netflix.simianarmy.janitor.TestAbstractJanitor.testJanitorWithCleanupFailure(TestAbstractJanitor.java:223)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)

Gradle test > com.netflix.simianarmy.basic.TestBasicCalendar.testGetBusinessDayWihHoliday FAILED
    java.lang.AssertionError at TestBasicCalendar.java:185

Gradle test > com.netflix.simianarmy.basic.TestBasicCalendar.testGetBusinessDayWihHolidayNextYear FAILED
    java.lang.AssertionError at TestBasicCalendar.java:204

Gradle test > com.netflix.simianarmy.basic.TestBasicCalendar.testGetBusinessDayWihWeekend FAILED
    java.lang.AssertionError at TestBasicCalendar.java:165

Gradle test > com.netflix.simianarmy.basic.TestBasicCalendar.testGetBusinessDayWihoutGap FAILED
    java.lang.AssertionError at TestBasicCalendar.java:145

**Comment by johnjelinek** [comment] 2015-03-11 21:59
I get this error too.

**Comment by johnjelinek** [comment] 2015-03-11 22:00
Duplicate of #146

**Comment by lantrix** [comment] 2015-05-05 03:16
I'm getting the same with these test cases. Commented them out for the time being.

**Closed** 2015-07-16 17:23 UTC
